### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mandarinenkater** [IAmPicard/StarTrekTimelinesSpreadsheet#82]
**Describe the bug**
Hello,

when I start the Picard tool I get the following error message. 

Try restarting the application; if the error persists, please log a bug. Details: Error: Network error; status 500; reply NoMethodError (undefined method `unslot_invalid_crew' for nil:NilClass): app/models/character.rb:626:in `init_ship' app/models/character.rb:562:in `block in setup' app/models/character.rb:560:in `setup' app/controllers/player_controller.rb:227:in `index' app/controllers/application_controller.rb:45:in `record_client_api' app/controllers/application_controller.rb:30:in `purge_thread_around'.

What am I doing wrong?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Tool version: **0.7.4**
Operating system: **win32 x64 (6.2.9200)**

Error details: Error: Network error; status 500; reply NoMethodError (undefined method `unslot_invalid_crew' for nil:NilClass):
app/models/character.rb:626:in `init_ship'
app/models/character.rb:562:in `block in setup'
app/models/character.rb:560:in `setup'
app/controllers/player_controller.rb:227:in `index'
app/controllers/application_controller.rb:45:in `record_client_api'
app/controllers/application_controller.rb:30:in `purge_thread_around'.

**Comment by mandarinenkater** [comment]
Edit: after a new deinstallation and deletion of all temp. and cache files, the tool works again
